variables:
    GOPATH: /go
    GOLANG_VERSION: "1.23.0"
    GOLINT_VERSION: "v1.60.3"

.gocache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
        - ${GOPATH}/pkg/mod
        - ${GOPATH}/bin

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == 'push'
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
    stage: build
    image: golang:${GOLANG_VERSION}
    needs: []
    cache: !reference [.gocache]
    script:
        - go mod download
        - go build ./...

lint:
    stage: test
    needs: [build]
    image: golangci/golangci-lint:${GOLINT_VERSION}
    script:
        - "! gofmt -l . | grep -q ."
        - golangci-lint run --timeout 5m0s

test:
    stage: test
    needs: [build]
    image: golang:${GOLANG_VERSION}
    cache: !reference [.gocache]
    script:
        - go test ./...
