// Code generated - DO NOT EDIT.

package defs

const (
	PathSet      XType = 18
	Transaction  XType = 10001
	Hash160      XType = 17
	LedgerEntry  XType = 10002
	NotPresent   XType = 0
	UInt512      XType = 23
	UInt64       XType = 3
	UInt8        XType = 16
	Currency     XType = 26
	STObject     XType = 14
	Hash192      XType = 21
	Metadata     XType = 10004
	UInt384      XType = 22
	AccountID    XType = 8
	Amount       XType = 6
	Blob         XType = 7
	Done         XType = -1
	Validation   XType = 10003
	Vector256    XType = 19
	Hash128      XType = 4
	UInt96       XType = 20
	STArray      XType = 15
	UInt32       XType = 2
	Unknown      XType = -2
	Issue        XType = 24
	Number       XType = 9
	XChainBridge XType = 25
	Hash256      XType = 5
	UInt16       XType = 1
)

var TxTypeToValue = map[string]int32{
	"OracleDelete":                      52,
	"PaymentChannelCreate":              13,
	"AMMCreate":                         35,
	"Clawback":                          30,
	"NFTokenCreateOffer":                27,
	"NFTokenModify":                     61,
	"PaymentChannelClaim":               15,
	"AccountDelete":                     21,
	"CheckCreate":                       16,
	"EscrowCreate":                      1,
	"XChainModifyBridge":                47,
	"AMMClawback":                       31,
	"MPTokenIssuanceSet":                56,
	"SetRegularKey":                     5,
	"CredentialDelete":                  60,
	"LedgerStateFix":                    53,
	"XChainCommit":                      42,
	"SetFee":                            101,
	"CredentialAccept":                  59,
	"DepositPreauth":                    19,
	"Payment":                           0,
	"PermissionedDomainDelete":          63,
	"XChainAddAccountCreateAttestation": 46,
	"AccountSet":                        3,
	"Invalid":                           -1,
	"OfferCreate":                       7,
	"AMMBid":                            39,
	"OfferCancel":                       8,
	"NFTokenAcceptOffer":                29,
	"AMMVote":                           38,
	"AMMWithdraw":                       37,
	"EnableAmendment":                   100,
	"NFTokenCancelOffer":                28,
	"XChainCreateBridge":                48,
	"PaymentChannelFund":                14,
	"TrustSet":                          20,
	"XChainAccountCreateCommit":         44,
	"AMMDeposit":                        36,
	"NFTokenBurn":                       26,
	"OracleSet":                         51,
	"PermissionedDomainSet":             62,
	"TicketCreate":                      10,
	"XChainClaim":                       43,
	"XChainCreateClaimID":               41,
	"CredentialCreate":                  58,
	"DIDDelete":                         50,
	"DIDSet":                            49,
	"EscrowCancel":                      4,
	"EscrowFinish":                      2,
	"MPTokenAuthorize":                  57,
	"MPTokenIssuanceDestroy":            55,
	"UNLModify":                         102,
	"XChainAddClaimAttestation":         45,
	"CheckCancel":                       18,
	"MPTokenIssuanceCreate":             54,
	"SignerListSet":                     12,
	"AMMDelete":                         40,
	"CheckCash":                         17,
	"NFTokenMint":                       25,
}

var NameToField = map[string]Field{
	"Generic": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            0,
		Type:           Unknown,
	},
	"Invalid": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            -1,
		Type:           Unknown,
	},
	"ObjectEndMarker": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           STObject,
	},
	"ArrayEndMarker": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           STArray,
	},
	"taker_gets_funded": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            258,
		Type:           Amount,
	},
	"taker_pays_funded": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            259,
		Type:           Amount,
	},
	"LedgerEntryType": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           UInt16,
	},
	"TransactionType": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           UInt16,
	},
	"SignerWeight": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           UInt16,
	},
	"TransferFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           UInt16,
	},
	"TradingFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           UInt16,
	},
	"DiscountedFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           UInt16,
	},
	"Version": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           UInt16,
	},
	"HookStateChangeCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           UInt16,
	},
	"HookEmitCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           UInt16,
	},
	"HookExecutionIndex": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           UInt16,
	},
	"HookApiVersion": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            20,
		Type:           UInt16,
	},
	"LedgerFixType": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           UInt16,
	},
	"NetworkID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           UInt32,
	},
	"Flags": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           UInt32,
	},
	"SourceTag": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           UInt32,
	},
	"Sequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           UInt32,
	},
	"PreviousTxnLgrSeq": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           UInt32,
	},
	"LedgerSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           UInt32,
	},
	"CloseTime": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           UInt32,
	},
	"ParentCloseTime": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           UInt32,
	},
	"SigningTime": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           UInt32,
	},
	"Expiration": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           UInt32,
	},
	"TransferRate": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           UInt32,
	},
	"WalletSize": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           UInt32,
	},
	"OwnerCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            13,
		Type:           UInt32,
	},
	"DestinationTag": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            14,
		Type:           UInt32,
	},
	"LastUpdateTime": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            15,
		Type:           UInt32,
	},
	"HighQualityIn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           UInt32,
	},
	"HighQualityOut": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           UInt32,
	},
	"LowQualityIn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           UInt32,
	},
	"LowQualityOut": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           UInt32,
	},
	"QualityIn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            20,
		Type:           UInt32,
	},
	"QualityOut": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           UInt32,
	},
	"StampEscrow": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           UInt32,
	},
	"BondAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            23,
		Type:           UInt32,
	},
	"LoadFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           UInt32,
	},
	"OfferSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           UInt32,
	},
	"FirstLedgerSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           UInt32,
	},
	"LastLedgerSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           UInt32,
	},
	"TransactionIndex": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           UInt32,
	},
	"OperationLimit": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            29,
		Type:           UInt32,
	},
	"ReferenceFeeUnits": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            30,
		Type:           UInt32,
	},
	"ReserveBase": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            31,
		Type:           UInt32,
	},
	"ReserveIncrement": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            32,
		Type:           UInt32,
	},
	"SetFlag": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            33,
		Type:           UInt32,
	},
	"ClearFlag": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            34,
		Type:           UInt32,
	},
	"SignerQuorum": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            35,
		Type:           UInt32,
	},
	"CancelAfter": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            36,
		Type:           UInt32,
	},
	"FinishAfter": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            37,
		Type:           UInt32,
	},
	"SignerListID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            38,
		Type:           UInt32,
	},
	"SettleDelay": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            39,
		Type:           UInt32,
	},
	"TicketCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            40,
		Type:           UInt32,
	},
	"TicketSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            41,
		Type:           UInt32,
	},
	"NFTokenTaxon": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            42,
		Type:           UInt32,
	},
	"MintedNFTokens": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            43,
		Type:           UInt32,
	},
	"BurnedNFTokens": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            44,
		Type:           UInt32,
	},
	"HookStateCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            45,
		Type:           UInt32,
	},
	"EmitGeneration": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            46,
		Type:           UInt32,
	},
	"VoteWeight": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            48,
		Type:           UInt32,
	},
	"FirstNFTokenSequence": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            50,
		Type:           UInt32,
	},
	"OracleDocumentID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            51,
		Type:           UInt32,
	},
	"IndexNext": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           UInt64,
	},
	"IndexPrevious": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           UInt64,
	},
	"BookNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           UInt64,
	},
	"OwnerNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           UInt64,
	},
	"BaseFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           UInt64,
	},
	"ExchangeRate": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           UInt64,
	},
	"LowNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           UInt64,
	},
	"HighNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           UInt64,
	},
	"DestinationNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           UInt64,
	},
	"Cookie": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           UInt64,
	},
	"ServerVersion": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           UInt64,
	},
	"NFTokenOfferNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           UInt64,
	},
	"EmitBurden": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            13,
		Type:           UInt64,
	},
	"HookOn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           UInt64,
	},
	"HookInstructionCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           UInt64,
	},
	"HookReturnCode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           UInt64,
	},
	"ReferenceCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           UInt64,
	},
	"XChainClaimID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            20,
		Type:           UInt64,
	},
	"XChainAccountCreateCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           UInt64,
	},
	"XChainAccountClaimCount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           UInt64,
	},
	"AssetPrice": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            23,
		Type:           UInt64,
	},
	"MaximumAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           UInt64,
	},
	"OutstandingAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           UInt64,
	},
	"MPTAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           UInt64,
	},
	"IssuerNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           UInt64,
	},
	"SubjectNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           UInt64,
	},
	"EmailHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Hash128,
	},
	"LedgerHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Hash256,
	},
	"ParentHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           Hash256,
	},
	"TransactionHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           Hash256,
	},
	"AccountHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           Hash256,
	},
	"PreviousTxnID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           Hash256,
	},
	"LedgerIndex": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           Hash256,
	},
	"WalletLocator": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           Hash256,
	},
	"RootIndex": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           Hash256,
	},
	"AccountTxnID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           Hash256,
	},
	"NFTokenID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           Hash256,
	},
	"EmitParentTxnID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           Hash256,
	},
	"EmitNonce": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           Hash256,
	},
	"EmitHookHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            13,
		Type:           Hash256,
	},
	"AMMID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            14,
		Type:           Hash256,
	},
	"BookDirectory": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           Hash256,
	},
	"InvoiceID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           Hash256,
	},
	"Nickname": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           Hash256,
	},
	"Amendment": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           Hash256,
	},
	"Digest": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           Hash256,
	},
	"Channel": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           Hash256,
	},
	"ConsensusHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            23,
		Type:           Hash256,
	},
	"CheckID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           Hash256,
	},
	"ValidatedHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           Hash256,
	},
	"PreviousPageMin": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           Hash256,
	},
	"NextPageMin": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           Hash256,
	},
	"NFTokenBuyOffer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           Hash256,
	},
	"NFTokenSellOffer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            29,
		Type:           Hash256,
	},
	"HookStateKey": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            30,
		Type:           Hash256,
	},
	"HookHash": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            31,
		Type:           Hash256,
	},
	"HookNamespace": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            32,
		Type:           Hash256,
	},
	"HookSetTxnID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            33,
		Type:           Hash256,
	},
	"DomainID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            34,
		Type:           Hash256,
	},
	"hash": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            257,
		Type:           Hash256,
	},
	"index": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            258,
		Type:           Hash256,
	},
	"Amount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Amount,
	},
	"Balance": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           Amount,
	},
	"LimitAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           Amount,
	},
	"TakerPays": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           Amount,
	},
	"TakerGets": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           Amount,
	},
	"LowLimit": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           Amount,
	},
	"HighLimit": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           Amount,
	},
	"Fee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           Amount,
	},
	"SendMax": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           Amount,
	},
	"DeliverMin": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           Amount,
	},
	"Amount2": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           Amount,
	},
	"BidMin": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           Amount,
	},
	"BidMax": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            13,
		Type:           Amount,
	},
	"MinimumOffer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           Amount,
	},
	"RippleEscrow": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           Amount,
	},
	"DeliveredAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           Amount,
	},
	"NFTokenBrokerFee": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           Amount,
	},
	"BaseFeeDrops": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           Amount,
	},
	"ReserveBaseDrops": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            23,
		Type:           Amount,
	},
	"ReserveIncrementDrops": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           Amount,
	},
	"LPTokenOut": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           Amount,
	},
	"LPTokenIn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           Amount,
	},
	"EPrice": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           Amount,
	},
	"Price": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           Amount,
	},
	"SignatureReward": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            29,
		Type:           Amount,
	},
	"MinAccountCreateAmount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            30,
		Type:           Amount,
	},
	"LPTokenBalance": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            31,
		Type:           Amount,
	},
	"PublicKey": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            1,
		Type:           Blob,
	},
	"MessageKey": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            2,
		Type:           Blob,
	},
	"SigningPubKey": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            3,
		Type:           Blob,
	},
	"TxnSignature": {
		IsSerialized:   true,
		IsSigningField: false,
		IsVLEncoded:    true,
		Nth:            4,
		Type:           Blob,
	},
	"URI": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            5,
		Type:           Blob,
	},
	"Signature": {
		IsSerialized:   true,
		IsSigningField: false,
		IsVLEncoded:    true,
		Nth:            6,
		Type:           Blob,
	},
	"Domain": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            7,
		Type:           Blob,
	},
	"FundCode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            8,
		Type:           Blob,
	},
	"RemoveCode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            9,
		Type:           Blob,
	},
	"ExpireCode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            10,
		Type:           Blob,
	},
	"CreateCode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            11,
		Type:           Blob,
	},
	"MemoType": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            12,
		Type:           Blob,
	},
	"MemoData": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            13,
		Type:           Blob,
	},
	"MemoFormat": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            14,
		Type:           Blob,
	},
	"Fulfillment": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            16,
		Type:           Blob,
	},
	"Condition": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            17,
		Type:           Blob,
	},
	"MasterSignature": {
		IsSerialized:   true,
		IsSigningField: false,
		IsVLEncoded:    true,
		Nth:            18,
		Type:           Blob,
	},
	"UNLModifyValidator": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            19,
		Type:           Blob,
	},
	"ValidatorToDisable": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            20,
		Type:           Blob,
	},
	"ValidatorToReEnable": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            21,
		Type:           Blob,
	},
	"HookStateData": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            22,
		Type:           Blob,
	},
	"HookReturnString": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            23,
		Type:           Blob,
	},
	"HookParameterName": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            24,
		Type:           Blob,
	},
	"HookParameterValue": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            25,
		Type:           Blob,
	},
	"DIDDocument": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            26,
		Type:           Blob,
	},
	"Data": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            27,
		Type:           Blob,
	},
	"AssetClass": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            28,
		Type:           Blob,
	},
	"Provider": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            29,
		Type:           Blob,
	},
	"MPTokenMetadata": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            30,
		Type:           Blob,
	},
	"CredentialType": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            31,
		Type:           Blob,
	},
	"Account": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            1,
		Type:           AccountID,
	},
	"Owner": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            2,
		Type:           AccountID,
	},
	"Destination": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            3,
		Type:           AccountID,
	},
	"Issuer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            4,
		Type:           AccountID,
	},
	"Authorize": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            5,
		Type:           AccountID,
	},
	"Unauthorize": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            6,
		Type:           AccountID,
	},
	"RegularKey": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            8,
		Type:           AccountID,
	},
	"NFTokenMinter": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            9,
		Type:           AccountID,
	},
	"EmitCallback": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            10,
		Type:           AccountID,
	},
	"Holder": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            11,
		Type:           AccountID,
	},
	"HookAccount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            16,
		Type:           AccountID,
	},
	"OtherChainSource": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            18,
		Type:           AccountID,
	},
	"OtherChainDestination": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            19,
		Type:           AccountID,
	},
	"AttestationSignerAccount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            20,
		Type:           AccountID,
	},
	"AttestationRewardAccount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            21,
		Type:           AccountID,
	},
	"LockingChainDoor": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            22,
		Type:           AccountID,
	},
	"IssuingChainDoor": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            23,
		Type:           AccountID,
	},
	"Subject": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            24,
		Type:           AccountID,
	},
	"Number": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Number,
	},
	"TransactionMetaData": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           STObject,
	},
	"CreatedNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           STObject,
	},
	"DeletedNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           STObject,
	},
	"ModifiedNode": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           STObject,
	},
	"PreviousFields": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           STObject,
	},
	"FinalFields": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           STObject,
	},
	"NewFields": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           STObject,
	},
	"TemplateEntry": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           STObject,
	},
	"Memo": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           STObject,
	},
	"SignerEntry": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           STObject,
	},
	"NFToken": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           STObject,
	},
	"EmitDetails": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            13,
		Type:           STObject,
	},
	"Hook": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            14,
		Type:           STObject,
	},
	"Signer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           STObject,
	},
	"Majority": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           STObject,
	},
	"DisabledValidator": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           STObject,
	},
	"EmittedTxn": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            20,
		Type:           STObject,
	},
	"HookExecution": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           STObject,
	},
	"HookDefinition": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           STObject,
	},
	"HookParameter": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            23,
		Type:           STObject,
	},
	"HookGrant": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           STObject,
	},
	"VoteEntry": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           STObject,
	},
	"AuctionSlot": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           STObject,
	},
	"AuthAccount": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           STObject,
	},
	"XChainClaimProofSig": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           STObject,
	},
	"XChainCreateAccountProofSig": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            29,
		Type:           STObject,
	},
	"XChainClaimAttestationCollectionElement": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            30,
		Type:           STObject,
	},
	"XChainCreateAccountAttestationCollectionElement": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            31,
		Type:           STObject,
	},
	"PriceData": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            32,
		Type:           STObject,
	},
	"Credential": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            33,
		Type:           STObject,
	},
	"Signers": {
		IsSerialized:   true,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           STArray,
	},
	"SignerEntries": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           STArray,
	},
	"Template": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           STArray,
	},
	"Necessary": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            6,
		Type:           STArray,
	},
	"Sufficient": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            7,
		Type:           STArray,
	},
	"AffectedNodes": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            8,
		Type:           STArray,
	},
	"Memos": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            9,
		Type:           STArray,
	},
	"NFTokens": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            10,
		Type:           STArray,
	},
	"Hooks": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            11,
		Type:           STArray,
	},
	"VoteSlots": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            12,
		Type:           STArray,
	},
	"Majorities": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           STArray,
	},
	"DisabledValidators": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           STArray,
	},
	"HookExecutions": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           STArray,
	},
	"HookParameters": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           STArray,
	},
	"HookGrants": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            20,
		Type:           STArray,
	},
	"XChainClaimAttestations": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            21,
		Type:           STArray,
	},
	"XChainCreateAccountAttestations": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            22,
		Type:           STArray,
	},
	"PriceDataSeries": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            24,
		Type:           STArray,
	},
	"AuthAccounts": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            25,
		Type:           STArray,
	},
	"AuthorizeCredentials": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            26,
		Type:           STArray,
	},
	"UnauthorizeCredentials": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            27,
		Type:           STArray,
	},
	"AcceptedCredentials": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            28,
		Type:           STArray,
	},
	"CloseResolution": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           UInt8,
	},
	"Method": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           UInt8,
	},
	"TransactionResult": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           UInt8,
	},
	"Scale": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           UInt8,
	},
	"AssetScale": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            5,
		Type:           UInt8,
	},
	"TickSize": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            16,
		Type:           UInt8,
	},
	"UNLModifyDisabling": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            17,
		Type:           UInt8,
	},
	"HookResult": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            18,
		Type:           UInt8,
	},
	"WasLockingChainSend": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            19,
		Type:           UInt8,
	},
	"TakerPaysCurrency": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Hash160,
	},
	"TakerPaysIssuer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           Hash160,
	},
	"TakerGetsCurrency": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           Hash160,
	},
	"TakerGetsIssuer": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           Hash160,
	},
	"Paths": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           PathSet,
	},
	"Indexes": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            1,
		Type:           Vector256,
	},
	"Hashes": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            2,
		Type:           Vector256,
	},
	"Amendments": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            3,
		Type:           Vector256,
	},
	"NFTokenOffers": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            4,
		Type:           Vector256,
	},
	"CredentialIDs": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    true,
		Nth:            5,
		Type:           Vector256,
	},
	"MPTokenIssuanceID": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Hash192,
	},
	"LockingChainIssue": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Issue,
	},
	"IssuingChainIssue": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           Issue,
	},
	"Asset": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            3,
		Type:           Issue,
	},
	"Asset2": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            4,
		Type:           Issue,
	},
	"XChainBridge": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           XChainBridge,
	},
	"BaseAsset": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            1,
		Type:           Currency,
	},
	"QuoteAsset": {
		IsSerialized:   true,
		IsSigningField: true,
		IsVLEncoded:    false,
		Nth:            2,
		Type:           Currency,
	},
	"Transaction": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            257,
		Type:           Transaction,
	},
	"LedgerEntry": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            257,
		Type:           LedgerEntry,
	},
	"Validation": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            257,
		Type:           Validation,
	},
	"Metadata": {
		IsSerialized:   false,
		IsSigningField: false,
		IsVLEncoded:    false,
		Nth:            257,
		Type:           Metadata,
	},
}
