package htlc

// TestHTLCTestVectors is a deterministic test that pins the HTLC witness
// script bytes, script size, and P2WSH addresses produced by BuildScript
// for a fixed (preimage, custodian key, timeout, n, k) tuple. Any change to
// the script encoding (byte layout, opcode choices) will break these vectors.
//
// The vectors are also published in the "Test vectors" appendix of
// docs/components/core-vault-btc.md. They are generated by this test and
// MUST be kept in sync with that appendix.
//
// Fixed parameters:
//   - preimageRaw: all-0xAA, 32 bytes
//   - custodianPub: makeFakePubKey(0x10) — deterministic secp256k1 point
//   - timeout: 1_700_000_000 (UNIX timestamp, well above the 500_000_000 minimum)
//   - multisigKeys: makeFakePubKey(0x20 + i) for i in 0..n-1
//   - k = ceil(n/2) per case

import (
	"encoding/hex"
	"testing"

	"github.com/btcsuite/btcd/chaincfg"
)

func TestHTLCTestVectors(t *testing.T) {
	var preimageRaw [32]byte
	for i := range preimageRaw {
		preimageRaw[i] = 0xAA
	}
	preimageHash := PreimageHash(preimageRaw)
	custodianPub := makeFakePubKey(0x10)
	timeout := int64(1_700_000_000)

	// Expected witness-script lengths:
	// Formula: 87 + 34*n for n ≤ 16 (OP_k and OP_n both fit in 1 byte).
	// For n > 16 (17..20), OP_n encodes as a 2-byte minimal push → +1 byte.
	// For k > 16, OP_k similarly → +1 byte. With k = ceil(n/2):
	//   n=3,  k=2:  87 + 102 = 189 (k,n ≤ 16)
	//   n=10, k=5:  87 + 340 = 427 (k,n ≤ 16)
	//   n=20, k=10: 87 + 680 + 1 = 768 (n=20 > 16 → OP_n 2 bytes; k=10 ≤ 16)

	cases := []struct {
		n           int
		k           int
		expectedLen int
		expectedHex string
		mainnetAddr string
		testnetAddr string
		regtestAddr string
	}{
		{
			n:           3,
			k:           2,
			expectedLen: 189,
			expectedHex: "6382012088a820e0e77a507412b120f6ede61f62295b1a7b2ff19d3dcc8f7253e51663470c888e8821023799f7f28db16bfffbbfd700814fe94eef8f33479b773b9a1f515e81b4116d2bac670400f15365b1695221021f8a566c205633d029094747d2e18f44e05993dda7a5f88f496078205f656e5921024c0c153fa0c946aa3ba2510b8bf4072f83f86eda3b61bc708f903a65727277b821031d17bd8d96b4bdf49dd1436e5af4f0bd3bff939df8cf8fdc1f621e3c89de2a4753ae68",
			mainnetAddr: "bc1q7d4c2ygjx23wtl6succnp9j22zjv0ueexpwdjcr3cyqh93mp56ns6hj4f2",
			testnetAddr: "tb1q7d4c2ygjx23wtl6succnp9j22zjv0ueexpwdjcr3cyqh93mp56nsdly6n9",
			regtestAddr: "bcrt1q7d4c2ygjx23wtl6succnp9j22zjv0ueexpwdjcr3cyqh93mp56nsqxwuxl",
		},
		{
			n:           10,
			k:           5,
			expectedLen: 427,
			expectedHex: "6382012088a820e0e77a507412b120f6ede61f62295b1a7b2ff19d3dcc8f7253e51663470c888e8821023799f7f28db16bfffbbfd700814fe94eef8f33479b773b9a1f515e81b4116d2bac670400f15365b1695521021f8a566c205633d029094747d2e18f44e05993dda7a5f88f496078205f656e5921024c0c153fa0c946aa3ba2510b8bf4072f83f86eda3b61bc708f903a65727277b821031d17bd8d96b4bdf49dd1436e5af4f0bd3bff939df8cf8fdc1f621e3c89de2a472102145eb6e6ef4edb7853aeffeec485cdd8e3fac803ad894d17e1ab0e22f954dc65210326212e514dcbeed82d3121a0b407b9ae0bd65f6ea68dfd74e5ade87244c18c9b21024a1e470b35b08cadddfd015aff598f19e8a179c0a9d4c252c1825d90d1701ecf21029b1277d1376697a7ffd3805cfc92e6ab5439e79ffbcef57b49967137e5d807b5210347e6bb0ff73539a09ffedf9d74df4cc4322d75cdcb120a9c56b9538e38fbfdf1210334866f7d6b2268d6972343034db667350273f8f973218c903286068aff4ac66d210360040c12b8a29ad5ea6754bc45db217017e5d042d38bbcd8f30002af003e752e5aae68",
			mainnetAddr: "bc1q904qzc7e3p2yvlkl6v3ny0cj7nz7jgtmygj2z63lgyd7j2np232svnv7cx",
			testnetAddr: "tb1q904qzc7e3p2yvlkl6v3ny0cj7nz7jgtmygj2z63lgyd7j2np232smm63zf",
			regtestAddr: "bcrt1q904qzc7e3p2yvlkl6v3ny0cj7nz7jgtmygj2z63lgyd7j2np232skzshhn",
		},
		{
			// n=20 k=10: OP_n for n=20 uses a 2-byte minimal push → +1 vs formula.
			n:           20,
			k:           10,
			expectedLen: 768,
			expectedHex: "6382012088a820e0e77a507412b120f6ede61f62295b1a7b2ff19d3dcc8f7253e51663470c888e8821023799f7f28db16bfffbbfd700814fe94eef8f33479b773b9a1f515e81b4116d2bac670400f15365b1695a21021f8a566c205633d029094747d2e18f44e05993dda7a5f88f496078205f656e5921024c0c153fa0c946aa3ba2510b8bf4072f83f86eda3b61bc708f903a65727277b821031d17bd8d96b4bdf49dd1436e5af4f0bd3bff939df8cf8fdc1f621e3c89de2a472102145eb6e6ef4edb7853aeffeec485cdd8e3fac803ad894d17e1ab0e22f954dc65210326212e514dcbeed82d3121a0b407b9ae0bd65f6ea68dfd74e5ade87244c18c9b21024a1e470b35b08cadddfd015aff598f19e8a179c0a9d4c252c1825d90d1701ecf21029b1277d1376697a7ffd3805cfc92e6ab5439e79ffbcef57b49967137e5d807b5210347e6bb0ff73539a09ffedf9d74df4cc4322d75cdcb120a9c56b9538e38fbfdf1210334866f7d6b2268d6972343034db667350273f8f973218c903286068aff4ac66d210360040c12b8a29ad5ea6754bc45db217017e5d042d38bbcd8f30002af003e752e21026805e4d6e2700ba2d9f14e2452a2c6459d7a495cea9c6fc89b5bd230de3c27d02103d04f9f7e96f439d392a52f319470052bd07aea48be0c5a68aa1c0e4fcb1dd1a1210325d8d1ad931285c9385893bf92681de668bf71ef2e8342f48bcd9d0c0311a1142102a989cd7c1b1bfb81518f99ed80dcf6c12424cf56dde98ecc2426b96b70d5c1d82102e1851ddaa51edc7ffc37886f2ad8b43ec7ebe9119561d5614740fdd4e0a10d45210276ca8753f0b4e7a926f5f273736d361fb16563ab611efa5e8e872d4eeafc55ab2103d66cc1afe6f5ef2dd4b44245e0d587501574bc3af08463a08af0fe7e7ea50b742103439702d790e192b1b192aa42c44300eed02833ef7cdc082e3a8bc8e682c9d732210327aada4b7abf7c5df07eb102fdc0522a4e6a3e5dce56b9696df22745912d8b2721033e165610444f4175e3d69393dc37367b9f7e21e09ac6264754bb78cce4af23030114ae68",
			mainnetAddr: "bc1qgnaxeu2c5d7fhgt5kssxq3n7af6yykvm7p9fr9mxr2tq4ueagsrq3sgjzq",
			testnetAddr: "tb1qgnaxeu2c5d7fhgt5kssxq3n7af6yykvm7p9fr9mxr2tq4ueagsrqxc7ac0",
			regtestAddr: "bcrt1qgnaxeu2c5d7fhgt5kssxq3n7af6yykvm7p9fr9mxr2tq4ueagsrqtp5md4",
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run("n=%d_k=%d", func(t *testing.T) {
			t.Helper()
			name := ""
			_ = name

			keys := make([][]byte, tc.n)
			for i := 0; i < tc.n; i++ {
				keys[i] = makeFakePubKey(byte(0x20 + i))
			}

			script, err := BuildScript(preimageHash, custodianPub, timeout, keys, tc.k)
			if err != nil {
				t.Fatalf("n=%d k=%d: BuildScript: %v", tc.n, tc.k, err)
			}

			// Script length
			if len(script) != tc.expectedLen {
				t.Errorf("n=%d k=%d: script len = %d, want %d", tc.n, tc.k, len(script), tc.expectedLen)
			}

			// Script hex (byte-exact)
			gotHex := hex.EncodeToString(script)
			if gotHex != tc.expectedHex {
				t.Errorf("n=%d k=%d: script hex mismatch\n  got:  %s\n  want: %s", tc.n, tc.k, gotHex, tc.expectedHex)
			}

			// P2WSH address per network
			addrMain, err := Address(script, &chaincfg.MainNetParams)
			if err != nil {
				t.Fatalf("mainnet addr: %v", err)
			}
			if addrMain.EncodeAddress() != tc.mainnetAddr {
				t.Errorf("mainnet addr: got %s, want %s", addrMain.EncodeAddress(), tc.mainnetAddr)
			}

			addrTest, err := Address(script, &chaincfg.TestNet3Params)
			if err != nil {
				t.Fatalf("testnet addr: %v", err)
			}
			if addrTest.EncodeAddress() != tc.testnetAddr {
				t.Errorf("testnet addr: got %s, want %s", addrTest.EncodeAddress(), tc.testnetAddr)
			}

			addrReg, err := Address(script, &chaincfg.RegressionNetParams)
			if err != nil {
				t.Fatalf("regtest addr: %v", err)
			}
			if addrReg.EncodeAddress() != tc.regtestAddr {
				t.Errorf("regtest addr: got %s, want %s", addrReg.EncodeAddress(), tc.regtestAddr)
			}
		})
	}
}

// TestHTLCWitnessHelpers verifies that HashPathWitness and
// TimeoutPathWitness produce the canonical witness stacks specified in
// docs/components/core-vault-btc.md §"Normative spend-path encodings".
func TestHTLCWitnessHelpers(t *testing.T) {
	script := []byte{0xDE, 0xAD, 0xBE, 0xEF} // stub witness script
	sig := []byte{0x30, 0x44, 0x01}          // stub sig
	var preimage [32]byte
	for i := range preimage {
		preimage[i] = 0xBB
	}

	t.Run("hash_path", func(t *testing.T) {
		w := HashPathWitness(sig, preimage, script)
		if len(w) != 4 {
			t.Fatalf("want 4 items, got %d", len(w))
		}
		// [0] sig
		if string(w[0]) != string(sig) {
			t.Error("[0] should be sig")
		}
		// [1] preimage (32 bytes)
		if len(w[1]) != 32 {
			t.Errorf("[1] preimage len = %d, want 32", len(w[1]))
		}
		// [2] {0x01} MINIMALIF selector
		if len(w[2]) != 1 || w[2][0] != 0x01 {
			t.Errorf("[2] want {0x01}, got %v", w[2])
		}
		// [3] witnessScript
		if string(w[3]) != string(script) {
			t.Error("[3] should be witnessScript")
		}
	})

	t.Run("timeout_path", func(t *testing.T) {
		sigs := [][]byte{sig, sig} // 2-of-3 example
		w := TimeoutPathWitness(sigs, script)
		if len(w) != 2+len(sigs)+1 {
			t.Fatalf("want %d items, got %d", 2+len(sigs)+1, len(w))
		}
		// [0] empty dummy (BIP-147 NULLDUMMY)
		if len(w[0]) != 0 {
			t.Errorf("[0] dummy must be empty (BIP-147), got %d bytes", len(w[0]))
		}
		// [1..k] sigs
		for i, s := range sigs {
			if string(w[i+1]) != string(s) {
				t.Errorf("[%d] sig mismatch", i+1)
			}
		}
		// [k+1] empty ELSE selector (MINIMALIF)
		elseItem := w[len(sigs)+1]
		if len(elseItem) != 0 {
			t.Errorf("[k+1] ELSE selector must be empty (MINIMALIF), got %v", elseItem)
		}
		// [k+2] witnessScript
		if string(w[len(sigs)+2]) != string(script) {
			t.Error("[k+2] should be witnessScript")
		}
	})
}
