//go:generate  abigen --abi=replication.abi --pkg=replication --type=TeeReplication --out=autogen.go
package replication

import "github.com/ethereum/go-ethereum/accounts/abi"

// Per-struct abi.Arguments exposed so callers can ABI-encode/decode the replication-flow
// payloads — pauseForUpgrade, replicateTeeMachine — without going through the autogenerated
// contract bindings.
var (
	PauseForUpgradeStructArg     abi.Argument
	ReplicateTeeMachineStructArg abi.Argument
)

func init() {
	replicationABI, err := TeeReplicationMetaData.GetAbi()
	if err != nil {
		panic(err)
	}

	for _, m := range []struct {
		method string
		arg    *abi.Argument
	}{
		{"pauseForUpgradeStruct", &PauseForUpgradeStructArg},
		{"replicateTeeMachineStruct", &ReplicateTeeMachineStructArg},
	} {
		method, ok := replicationABI.Methods[m.method]
		if !ok {
			panic("missing method " + m.method)
		}
		*m.arg = method.Inputs[0]
	}
}
