//go:generate  abigen --abi=upgrade.abi --pkg=upgrade --type=TeeUpgrade --out=autogen.go
package upgrade

import "github.com/ethereum/go-ethereum/accounts/abi"

// Per-struct abi.Arguments exposed so callers can ABI-encode/decode the upgrade-flow
// payloads — pauseForUpgrade, replicateTeeMachine, teeNodeVersion, teeUpgradePath —
// without going through the autogenerated contract bindings.
var (
	PauseForUpgradeStructArg     abi.Argument
	ReplicateTeeMachineStructArg abi.Argument
	TeeNodeVersionStructArg      abi.Argument
	TeeUpgradePathStructArg      abi.Argument
)

func init() {
	upgradeABI, err := TeeUpgradeMetaData.GetAbi()
	if err != nil {
		panic(err)
	}

	for _, m := range []struct {
		method string
		arg    *abi.Argument
	}{
		{"pauseForUpgradeStruct", &PauseForUpgradeStructArg},
		{"replicateTeeMachineStruct", &ReplicateTeeMachineStructArg},
		{"teeNodeVersionStruct", &TeeNodeVersionStructArg},
		{"teeUpgradePathStruct", &TeeUpgradePathStructArg},
	} {
		method, ok := upgradeABI.Methods[m.method]
		if !ok {
			panic("missing method " + m.method)
		}
		*m.arg = method.Inputs[0]
	}
}
